global:
  scrape_interval: 10s

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['service:9100'] # NOT localhost since we named the host of service in docker-compose file
- job_name: docker
  static_configs:
  - targets: ['cadvisor:8080'] # NOT localhost since we named the host of service in docker-compose file
- job_name: redis
  static_configs:
  - targets: ['redis_exporter:9121'] # NOT localhost since we named the host of service in docker-compose file